// Mocks generated by Mockito 5.4.6 from annotations
// in drishti_mobile_app/test/voice_navigation/theme_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:ui' as _i8;

import 'package:drishti_mobile_app/core/themes/theme_provider.dart' as _i7;
import 'package:drishti_mobile_app/data/services/voice_navigation/audio_feedback_engine.dart'
    as _i4;
import 'package:flutter/foundation.dart' as _i3;
import 'package:flutter/material.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeThemeData_0 extends _i1.SmartFake implements _i2.ThemeData {
  _FakeThemeData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);

  @override
  String toString({_i3.DiagnosticLevel? minLevel = _i3.DiagnosticLevel.info}) =>
      super.toString();
}

/// A class which mocks [AudioFeedbackEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioFeedbackEngine extends _i1.Mock
    implements _i4.AudioFeedbackEngine {
  MockAudioFeedbackEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSpeaking =>
      (super.noSuchMethod(Invocation.getter(#isSpeaking), returnValue: false)
          as bool);

  @override
  int get queueLength =>
      (super.noSuchMethod(Invocation.getter(#queueLength), returnValue: 0)
          as int);

  @override
  _i5.Future<void> speak(
    String? message, {
    _i4.AudioPriority? priority = _i4.AudioPriority.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [message], {#priority: priority}),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> speakImmediate(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#speakImmediate, [message]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> announceScreen(String? screenName, List<String>? actions) =>
      (super.noSuchMethod(
            Invocation.method(#announceScreen, [screenName, actions]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> confirmAction(String? action) =>
      (super.noSuchMethod(
            Invocation.method(#confirmAction, [action]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> reportError(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#reportError, [error]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> announceNavigation(String? destination) =>
      (super.noSuchMethod(
            Invocation.method(#announceNavigation, [destination]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  String formatVisionResponse(String? rawResponse) =>
      (super.noSuchMethod(
            Invocation.method(#formatVisionResponse, [rawResponse]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#formatVisionResponse, [rawResponse]),
            ),
          )
          as String);

  @override
  String formatErrorMessage(String? technicalError) =>
      (super.noSuchMethod(
            Invocation.method(#formatErrorMessage, [technicalError]),
            returnValue: _i6.dummyValue<String>(
              this,
              Invocation.method(#formatErrorMessage, [technicalError]),
            ),
          )
          as String);

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> stopSpeaking() =>
      (super.noSuchMethod(
            Invocation.method(#stopSpeaking, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ThemeProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockThemeProvider extends _i1.Mock implements _i7.ThemeProvider {
  MockThemeProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i7.ThemeType get themeType =>
      (super.noSuchMethod(
            Invocation.getter(#themeType),
            returnValue: _i7.ThemeType.light,
          )
          as _i7.ThemeType);

  @override
  _i2.ThemeData get themeData =>
      (super.noSuchMethod(
            Invocation.getter(#themeData),
            returnValue: _FakeThemeData_0(this, Invocation.getter(#themeData)),
          )
          as _i2.ThemeData);

  @override
  bool get isDarkMode =>
      (super.noSuchMethod(Invocation.getter(#isDarkMode), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  void updateSystemTheme(_i8.Brightness? brightness) => super.noSuchMethod(
    Invocation.method(#updateSystemTheme, [brightness]),
    returnValueForMissingStub: null,
  );

  @override
  _i5.Future<void> setTheme(_i7.ThemeType? type) =>
      (super.noSuchMethod(
            Invocation.method(#setTheme, [type]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> toggleTheme() =>
      (super.noSuchMethod(
            Invocation.method(#toggleTheme, []),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}
