// Mocks generated by Mockito 5.4.6 from annotations
// in drishti_mobile_app/test/voice_navigation/unrecognized_command_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drishti_mobile_app/data/services/voice_navigation/audio_feedback_engine.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [AudioFeedbackEngine].
///
/// See the documentation for Mockito's code generation for more information.
class MockAudioFeedbackEngine extends _i1.Mock
    implements _i2.AudioFeedbackEngine {
  MockAudioFeedbackEngine() {
    _i1.throwOnMissingStub(this);
  }

  @override
  bool get isSpeaking =>
      (super.noSuchMethod(Invocation.getter(#isSpeaking), returnValue: false)
          as bool);

  @override
  int get queueLength =>
      (super.noSuchMethod(Invocation.getter(#queueLength), returnValue: 0)
          as int);

  @override
  _i3.Future<void> speak(
    String? message, {
    _i2.AudioPriority? priority = _i2.AudioPriority.normal,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [message], {#priority: priority}),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> speakImmediate(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#speakImmediate, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announceScreen(String? screenName, List<String>? actions) =>
      (super.noSuchMethod(
            Invocation.method(#announceScreen, [screenName, actions]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> confirmAction(String? action) =>
      (super.noSuchMethod(
            Invocation.method(#confirmAction, [action]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> reportError(String? error) =>
      (super.noSuchMethod(
            Invocation.method(#reportError, [error]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announceNavigation(String? destination) =>
      (super.noSuchMethod(
            Invocation.method(#announceNavigation, [destination]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  String formatVisionResponse(String? rawResponse) =>
      (super.noSuchMethod(
            Invocation.method(#formatVisionResponse, [rawResponse]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#formatVisionResponse, [rawResponse]),
            ),
          )
          as String);

  @override
  String formatErrorMessage(String? technicalError) =>
      (super.noSuchMethod(
            Invocation.method(#formatErrorMessage, [technicalError]),
            returnValue: _i4.dummyValue<String>(
              this,
              Invocation.method(#formatErrorMessage, [technicalError]),
            ),
          )
          as String);

  @override
  void clearQueue() => super.noSuchMethod(
    Invocation.method(#clearQueue, []),
    returnValueForMissingStub: null,
  );

  @override
  _i3.Future<void> stopSpeaking() =>
      (super.noSuchMethod(
            Invocation.method(#stopSpeaking, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
