// Mocks generated by Mockito 5.4.6 from annotations
// in drishti_mobile_app/test/screens/model_download_screen_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i8;

import 'package:drishti_mobile_app/data/providers/vlm_provider.dart' as _i3;
import 'package:drishti_mobile_app/data/services/local_vlm_service.dart' as _i2;
import 'package:drishti_mobile_app/data/services/voice_service.dart' as _i9;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVLMResponse_0 extends _i1.SmartFake implements _i2.VLMResponse {
  _FakeVLMResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVLMChatMessage_1 extends _i1.SmartFake
    implements _i2.VLMChatMessage {
  _FakeVLMChatMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [VLMProvider].
///
/// See the documentation for Mockito's code generation for more information.
class MockVLMProvider extends _i1.Mock implements _i3.VLMProvider {
  MockVLMProvider() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.VLMStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i2.VLMStatus.uninitialized,
          )
          as _i2.VLMStatus);

  @override
  double get progress =>
      (super.noSuchMethod(Invocation.getter(#progress), returnValue: 0.0)
          as double);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> get areModelsDownloaded =>
      (super.noSuchMethod(
            Invocation.getter(#areModelsDownloaded),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> get downloadedModelSize =>
      (super.noSuchMethod(
            Invocation.getter(#downloadedModelSize),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  List<_i2.VLMChatMessage> get chatHistory =>
      (super.noSuchMethod(
            Invocation.getter(#chatHistory),
            returnValue: <_i2.VLMChatMessage>[],
          )
          as List<_i2.VLMChatMessage>);

  @override
  bool get isGenerating =>
      (super.noSuchMethod(Invocation.getter(#isGenerating), returnValue: false)
          as bool);

  @override
  _i4.Stream<String> get tokenStream =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<void> downloadModelsIfNeeded() =>
      (super.noSuchMethod(
            Invocation.method(#downloadModelsIfNeeded, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initialize() =>
      (super.noSuchMethod(
            Invocation.method(#initialize, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> ensureReady() =>
      (super.noSuchMethod(
            Invocation.method(#ensureReady, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.VLMResponse> analyzeImage({
    required _i5.Uint8List? imageBytes,
    String? prompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImage, [], {
              #imageBytes: imageBytes,
              #prompt: prompt,
            }),
            returnValue: _i4.Future<_i2.VLMResponse>.value(
              _FakeVLMResponse_0(
                this,
                Invocation.method(#analyzeImage, [], {
                  #imageBytes: imageBytes,
                  #prompt: prompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.VLMResponse>);

  @override
  _i4.Future<_i2.VLMResponse> analyzeImageFromFile({
    required _i6.File? imageFile,
    String? prompt,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImageFromFile, [], {
              #imageFile: imageFile,
              #prompt: prompt,
            }),
            returnValue: _i4.Future<_i2.VLMResponse>.value(
              _FakeVLMResponse_0(
                this,
                Invocation.method(#analyzeImageFromFile, [], {
                  #imageFile: imageFile,
                  #prompt: prompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.VLMResponse>);

  @override
  _i4.Future<void> stopInference() =>
      (super.noSuchMethod(
            Invocation.method(#stopInference, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearContext() => super.noSuchMethod(
    Invocation.method(#clearContext, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> deleteModels() =>
      (super.noSuchMethod(
            Invocation.method(#deleteModels, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String> describeForAccessibility(_i5.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#describeForAccessibility, [imageBytes]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#describeForAccessibility, [imageBytes]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> identifyObjects(_i5.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#identifyObjects, [imageBytes]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#identifyObjects, [imageBytes]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> readText(_i5.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#readText, [imageBytes]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#readText, [imageBytes]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<String> describeForNavigation(_i5.Uint8List? imageBytes) =>
      (super.noSuchMethod(
            Invocation.method(#describeForNavigation, [imageBytes]),
            returnValue: _i4.Future<String>.value(
              _i7.dummyValue<String>(
                this,
                Invocation.method(#describeForNavigation, [imageBytes]),
              ),
            ),
          )
          as _i4.Future<String>);

  @override
  _i4.Future<void> startNewChat(_i6.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#startNewChat, [imageFile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.VLMChatMessage> sendChatMessage(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#sendChatMessage, [message]),
            returnValue: _i4.Future<_i2.VLMChatMessage>.value(
              _FakeVLMChatMessage_1(
                this,
                Invocation.method(#sendChatMessage, [message]),
              ),
            ),
          )
          as _i4.Future<_i2.VLMChatMessage>);

  @override
  void clearChat() => super.noSuchMethod(
    Invocation.method(#clearChat, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  void addListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i8.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i9.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<double> get audioLevelStream =>
      (super.noSuchMethod(
            Invocation.getter(#audioLevelStream),
            returnValue: _i4.Stream<double>.empty(),
          )
          as _i4.Stream<double>);

  @override
  double get speechRate =>
      (super.noSuchMethod(Invocation.getter(#speechRate), returnValue: 0.0)
          as double);

  @override
  double get pitch =>
      (super.noSuchMethod(Invocation.getter(#pitch), returnValue: 0.0)
          as double);

  @override
  double get volume =>
      (super.noSuchMethod(Invocation.getter(#volume), returnValue: 0.0)
          as double);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  bool get isSttAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isSttAvailable),
            returnValue: false,
          )
          as bool);

  @override
  bool get isHotwordListening =>
      (super.noSuchMethod(
            Invocation.getter(#isHotwordListening),
            returnValue: false,
          )
          as bool);

  @override
  bool get isContinuousListening =>
      (super.noSuchMethod(
            Invocation.getter(#isContinuousListening),
            returnValue: false,
          )
          as bool);

  @override
  bool get isSttListening =>
      (super.noSuchMethod(
            Invocation.getter(#isSttListening),
            returnValue: false,
          )
          as bool);

  @override
  _i4.Future<void> initTts() =>
      (super.noSuchMethod(
            Invocation.method(#initTts, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> initStt() =>
      (super.noSuchMethod(
            Invocation.method(#initStt, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopSpeaking() =>
      (super.noSuchMethod(
            Invocation.method(#stopSpeaking, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setSpeechRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeechRate, [rate]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> startListening({
    required dynamic Function(String)? onResult,
    dynamic Function(String)? onError,
    Duration? listenFor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startListening, [], {
              #onResult: onResult,
              #onError: onError,
              #listenFor: listenFor,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopListening() =>
      (super.noSuchMethod(
            Invocation.method(#stopListening, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> cancelListening() =>
      (super.noSuchMethod(
            Invocation.method(#cancelListening, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> announce(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#announce, [message]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> readAlert(String? description, String? severity) =>
      (super.noSuchMethod(
            Invocation.method(#readAlert, [description, severity]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> startHotwordListening({
    required dynamic Function()? onHotwordDetected,
    dynamic Function(String)? onContinuousSpeech,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startHotwordListening, [], {
              #onHotwordDetected: onHotwordDetected,
              #onContinuousSpeech: onContinuousSpeech,
            }),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> stopHotwordListening() =>
      (super.noSuchMethod(
            Invocation.method(#stopHotwordListening, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> resumeHotwordListening() =>
      (super.noSuchMethod(
            Invocation.method(#resumeHotwordListening, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);
}
