// Mocks generated by Mockito 5.4.6 from annotations
// in drishti_mobile_app/test/data/services/voice_navigation/microphone_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:drishti_mobile_app/data/services/voice_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [VoiceService].
///
/// See the documentation for Mockito's code generation for more information.
class MockVoiceService extends _i1.Mock implements _i2.VoiceService {
  MockVoiceService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Stream<double> get audioLevelStream =>
      (super.noSuchMethod(
            Invocation.getter(#audioLevelStream),
            returnValue: _i3.Stream<double>.empty(),
          )
          as _i3.Stream<double>);

  @override
  double get speechRate =>
      (super.noSuchMethod(Invocation.getter(#speechRate), returnValue: 0.0)
          as double);

  @override
  double get pitch =>
      (super.noSuchMethod(Invocation.getter(#pitch), returnValue: 0.0)
          as double);

  @override
  double get volume =>
      (super.noSuchMethod(Invocation.getter(#volume), returnValue: 0.0)
          as double);

  @override
  bool get isListening =>
      (super.noSuchMethod(Invocation.getter(#isListening), returnValue: false)
          as bool);

  @override
  bool get isSttAvailable =>
      (super.noSuchMethod(
            Invocation.getter(#isSttAvailable),
            returnValue: false,
          )
          as bool);

  @override
  _i3.Future<void> initTts() =>
      (super.noSuchMethod(
            Invocation.method(#initTts, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<bool> initStt() =>
      (super.noSuchMethod(
            Invocation.method(#initStt, []),
            returnValue: _i3.Future<bool>.value(false),
          )
          as _i3.Future<bool>);

  @override
  _i3.Future<void> speak(String? text) =>
      (super.noSuchMethod(
            Invocation.method(#speak, [text]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopSpeaking() =>
      (super.noSuchMethod(
            Invocation.method(#stopSpeaking, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setSpeechRate(double? rate) =>
      (super.noSuchMethod(
            Invocation.method(#setSpeechRate, [rate]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setPitch(double? pitch) =>
      (super.noSuchMethod(
            Invocation.method(#setPitch, [pitch]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> setVolume(double? volume) =>
      (super.noSuchMethod(
            Invocation.method(#setVolume, [volume]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> startListening({
    required dynamic Function(String)? onResult,
    dynamic Function(String)? onError,
    Duration? listenFor,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#startListening, [], {
              #onResult: onResult,
              #onError: onError,
              #listenFor: listenFor,
            }),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> stopListening() =>
      (super.noSuchMethod(
            Invocation.method(#stopListening, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> cancelListening() =>
      (super.noSuchMethod(
            Invocation.method(#cancelListening, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> announce(String? message) =>
      (super.noSuchMethod(
            Invocation.method(#announce, [message]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> readAlert(String? description, String? severity) =>
      (super.noSuchMethod(
            Invocation.method(#readAlert, [description, severity]),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);

  @override
  _i3.Future<void> dispose() =>
      (super.noSuchMethod(
            Invocation.method(#dispose, []),
            returnValue: _i3.Future<void>.value(),
            returnValueForMissingStub: _i3.Future<void>.value(),
          )
          as _i3.Future<void>);
}
