// Mocks generated by Mockito 5.4.6 from annotations
// in drishti_mobile_app/test/voice_service/hotword_restart_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;
import 'dart:io' as _i6;
import 'dart:typed_data' as _i5;
import 'dart:ui' as _i7;

import 'package:dio/dio.dart' as _i3;
import 'package:drishti_mobile_app/data/services/api_service.dart' as _i8;
import 'package:drishti_mobile_app/data/services/local_vlm_service.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeVLMResponse_0 extends _i1.SmartFake implements _i2.VLMResponse {
  _FakeVLMResponse_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeVLMChatMessage_1 extends _i1.SmartFake
    implements _i2.VLMChatMessage {
  _FakeVLMChatMessage_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeResponse_2<T> extends _i1.SmartFake implements _i3.Response<T> {
  _FakeResponse_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [LocalVLMService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocalVLMService extends _i1.Mock implements _i2.LocalVLMService {
  MockLocalVLMService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Stream<String> get tokenStream =>
      (super.noSuchMethod(
            Invocation.getter(#tokenStream),
            returnValue: _i4.Stream<String>.empty(),
          )
          as _i4.Stream<String>);

  @override
  List<_i2.VLMChatMessage> get chatHistory =>
      (super.noSuchMethod(
            Invocation.getter(#chatHistory),
            returnValue: <_i2.VLMChatMessage>[],
          )
          as List<_i2.VLMChatMessage>);

  @override
  bool get isGenerating =>
      (super.noSuchMethod(Invocation.getter(#isGenerating), returnValue: false)
          as bool);

  @override
  _i2.VLMStatus get status =>
      (super.noSuchMethod(
            Invocation.getter(#status),
            returnValue: _i2.VLMStatus.uninitialized,
          )
          as _i2.VLMStatus);

  @override
  double get loadProgress =>
      (super.noSuchMethod(Invocation.getter(#loadProgress), returnValue: 0.0)
          as double);

  @override
  bool get isReady =>
      (super.noSuchMethod(Invocation.getter(#isReady), returnValue: false)
          as bool);

  @override
  bool get hasListeners =>
      (super.noSuchMethod(Invocation.getter(#hasListeners), returnValue: false)
          as bool);

  @override
  _i4.Future<bool> areModelsDownloaded() =>
      (super.noSuchMethod(
            Invocation.method(#areModelsDownloaded, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<int> getDownloadedModelSize() =>
      (super.noSuchMethod(
            Invocation.method(#getDownloadedModelSize, []),
            returnValue: _i4.Future<int>.value(0),
          )
          as _i4.Future<int>);

  @override
  _i4.Future<void> downloadModels({_i2.VLMProgressCallback? onProgress}) =>
      (super.noSuchMethod(
            Invocation.method(#downloadModels, [], {#onProgress: onProgress}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<void> initialize({_i2.VLMProgressCallback? onProgress}) =>
      (super.noSuchMethod(
            Invocation.method(#initialize, [], {#onProgress: onProgress}),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.VLMResponse> analyzeImage({
    required _i5.Uint8List? imageBytes,
    String? prompt = 'Describe what you see in this image in detail.',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImage, [], {
              #imageBytes: imageBytes,
              #prompt: prompt,
            }),
            returnValue: _i4.Future<_i2.VLMResponse>.value(
              _FakeVLMResponse_0(
                this,
                Invocation.method(#analyzeImage, [], {
                  #imageBytes: imageBytes,
                  #prompt: prompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.VLMResponse>);

  @override
  _i4.Future<_i2.VLMResponse> analyzeImageFromFile({
    required _i6.File? imageFile,
    String? prompt = 'Describe what you see in this image in detail.',
  }) =>
      (super.noSuchMethod(
            Invocation.method(#analyzeImageFromFile, [], {
              #imageFile: imageFile,
              #prompt: prompt,
            }),
            returnValue: _i4.Future<_i2.VLMResponse>.value(
              _FakeVLMResponse_0(
                this,
                Invocation.method(#analyzeImageFromFile, [], {
                  #imageFile: imageFile,
                  #prompt: prompt,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.VLMResponse>);

  @override
  _i4.Future<void> stopInference() =>
      (super.noSuchMethod(
            Invocation.method(#stopInference, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void clearContext() => super.noSuchMethod(
    Invocation.method(#clearContext, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> startNewChat(_i6.File? imageFile) =>
      (super.noSuchMethod(
            Invocation.method(#startNewChat, [imageFile]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<_i2.VLMChatMessage> sendChatMessage(String? userMessage) =>
      (super.noSuchMethod(
            Invocation.method(#sendChatMessage, [userMessage]),
            returnValue: _i4.Future<_i2.VLMChatMessage>.value(
              _FakeVLMChatMessage_1(
                this,
                Invocation.method(#sendChatMessage, [userMessage]),
              ),
            ),
          )
          as _i4.Future<_i2.VLMChatMessage>);

  @override
  void clearChat() => super.noSuchMethod(
    Invocation.method(#clearChat, []),
    returnValueForMissingStub: null,
  );

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );

  @override
  _i4.Future<void> deleteModels() =>
      (super.noSuchMethod(
            Invocation.method(#deleteModels, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  void addListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#addListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void removeListener(_i7.VoidCallback? listener) => super.noSuchMethod(
    Invocation.method(#removeListener, [listener]),
    returnValueForMissingStub: null,
  );

  @override
  void notifyListeners() => super.noSuchMethod(
    Invocation.method(#notifyListeners, []),
    returnValueForMissingStub: null,
  );
}

/// A class which mocks [ApiService].
///
/// See the documentation for Mockito's code generation for more information.
class MockApiService extends _i1.Mock implements _i8.ApiService {
  MockApiService() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<void> setToken(String? token) =>
      (super.noSuchMethod(
            Invocation.method(#setToken, [token]),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<String?> getToken() =>
      (super.noSuchMethod(
            Invocation.method(#getToken, []),
            returnValue: _i4.Future<String?>.value(),
          )
          as _i4.Future<String?>);

  @override
  _i4.Future<void> clearToken() =>
      (super.noSuchMethod(
            Invocation.method(#clearToken, []),
            returnValue: _i4.Future<void>.value(),
            returnValueForMissingStub: _i4.Future<void>.value(),
          )
          as _i4.Future<void>);

  @override
  _i4.Future<bool> isAuthenticated() =>
      (super.noSuchMethod(
            Invocation.method(#isAuthenticated, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);

  @override
  _i4.Future<_i3.Response<dynamic>> get(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #get,
              [endpoint],
              {#queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #get,
                  [endpoint],
                  {#queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> post(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #post,
              [endpoint],
              {#data: data, #queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #post,
                  [endpoint],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> put(
    String? endpoint, {
    dynamic data,
    Map<String, dynamic>? queryParameters,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #put,
              [endpoint],
              {#data: data, #queryParameters: queryParameters},
            ),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #put,
                  [endpoint],
                  {#data: data, #queryParameters: queryParameters},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> delete(
    String? endpoint, {
    Map<String, dynamic>? queryParameters,
    Map<String, dynamic>? data,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #delete,
              [endpoint],
              {#queryParameters: queryParameters, #data: data},
            ),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(
                  #delete,
                  [endpoint],
                  {#queryParameters: queryParameters, #data: data},
                ),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<_i3.Response<dynamic>> postFormData(
    String? endpoint,
    _i3.FormData? formData,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#postFormData, [endpoint, formData]),
            returnValue: _i4.Future<_i3.Response<dynamic>>.value(
              _FakeResponse_2<dynamic>(
                this,
                Invocation.method(#postFormData, [endpoint, formData]),
              ),
            ),
          )
          as _i4.Future<_i3.Response<dynamic>>);

  @override
  _i4.Future<bool> checkHealth() =>
      (super.noSuchMethod(
            Invocation.method(#checkHealth, []),
            returnValue: _i4.Future<bool>.value(false),
          )
          as _i4.Future<bool>);
}
